### ISSUE TITLE
Correct the errors of the report

### ISSUE THREAD

**Issue by Park-Joonyoung** [arduinocc04/AAC#38]
Blur/Morphology -> Binary (X) | Blur -> Binary or Binary -> Morphology (O)
CCW sorting only (X) | CW sorting only (O)
Uses Gaussian-blur one more time before transforming the coordinate into log-polar.
Update README? When we have enough time to deal with it

**Comment by Park-Joonyoung** [comment]
Done
1, 2, 3: by @Park-Joonyoung 
4: by @arduinocc04

**Comment by arduinocc04** [comment]
ㅋㅋㅋㅋ 아니 readme 업데이트 하는 것도 목표에 있는 줄 몰랐네
